version: '3.7'

services:
  ingestor:
    image: diouze/log-ingestor
    ports:
      - 8080
    environment:
      - SERVICE_PORTS=8080
    deploy:
      replicas: 6
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    networks:
      - log-network
    volumes:
      - ./data/ingestor:/data
  consolidator:
    image: diouze/log-consolidator
    depends_on:
      - ingestor
      - minio
    ports:
      - 3333:8080
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    networks:
      - log-network
    volumes:
      - ./data/consolidator:/data
  proxy:
    image: dockercloud/haproxy
    depends_on:
      - ingestor
    environment:
      - BALANCE=roundrobin
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
    networks:
      - log-network
    deploy:
      placement:
        constraints: [node.role == manager]
  minio:
    image: minio/minio
    networks:
      - log-network
    ports:
      - "9001:9000"
    command: server /data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    volumes:
      - ./data/minio:/data
networks:
  log-network:
    driver: overlay